### ISSUE TITLE
Break command coordinates to block sometimes turn out to be wrong.

### ISSUE THREAD

**Issue by MairwunNx** [ProjectEssentials/ProjectEssentials#1]
In it line ([link](https://github.com/MairwunNx/ProjectEssentials/blob/18768cb445adfcffd18afa75832abaad92aa3b89/src/main/kotlin/com/mairwunnx/projectessentials/commands/BreakCommand.kt#L46 )) has small problem: 
> #### the coordinates of the block I'm looking at do not always turn out to be correct.

I tried round to int each coordinate in `Vec3d`, it little fix this problem, but not in all cases.
I think problem precisely in it code, but maybe I'm wrong.

![image](https://user-images.githubusercontent.com/39625750/65390278-365d5600-dd66-11e9-80e7-87cd095ed405.png)

Sometimes a vector is 1 larger in some coordinate than necessary. Perhaps there is a better solution to implement this feature.

**Comment by MairwunNx** [comment]
I'll just close this lol, i think this command is redundant, this command will removed in 2.X and this issue will closed.

**Comment by saputraGTX** [comment]
https://github.com/github/opensource.guide/actions/workflows/tests.yml/badge.svg
