### ISSUE TITLE
'/invsee' and '/enderchest' feature request

### ISSUE THREAD

**Issue by TetraTheta** [ProjectEssentials/ProjectEssentials#22]
There are `/invsee <player>` and `/encherchest <player>` commands in Essentials(or EssentialsX). I hope these commands would be present in Project Essentials.
`/invsee` can see player's inventory and `/enderchest` can see player's enderchest.

If OP(or player with proper permission) issue the command `/invsee <player>`, he can open the player's inventory and armor/shield slot. If issuer has another permission that enables edit the inventory, he can edit the player's inventory. If the player acquire item while OP is opening his inventory, the acquired item should be shown in OP's screen(synchronized).

If synchronization cannot be achieved, that would be OK because OP can just re-issue the command and get updated the player's inventory information.

I remember that player's whole inventory is shown in 4x9 GUI. first 3x9 is player's inventory and last 9 slots are player's armor and shield slot.

**Comment by TetraTheta** [comment]
There is #19 but this feature request is superset of the request because this request contains `/enderchest` feature request so I think I should not close this issue.

**Comment by MairwunNx** [comment]
Thanks for issue 👋, @TetraTheta!

I started working on it. But i have few questions.

**But then some items do not fit into the displayed inventory, what about this?**
> I remember that player's whole inventory is shown in 4x9 GUI. first 3x9 is player's inventory and last 9 slots are player's armor and shield slot.

If this command will work correctly it will able for testing in Release Candidate 1 (2.0.0-RC.1) or in first snapshot build. You will notified about any releases if you click on `watch` button.

*This issue will closed when I implement all features described in this issue.*

**Comment by MairwunNx** [comment]
Enderchest command implemented in https://github.com/ProjectEssentials/ProjectEssentials/commit/72acc155b13fde8d3dde35ce519e3391812453d5

**Comment by TetraTheta** [comment]
> But then some items do not fit into the displayed inventory, what about this?

My mistake. Player's inventory including quick slot is 4x9 so total grid size would be 5x9.

As far as I know, there wasn't additional feature that 'overflow' the 5x9 grid in EssentialsX. But this mod, Project Essentials is Forge mod. Some mods implement additional inventory slot that might not shown in given 5x9 grid.

Then can we modify the requested command that can handle it?

`/invsee <player> [enderchest|baubles]` like this. I can't remember other sort of mods that add custom inventory to player so I just added Baubles for example. If second argument(first is player nickname) isn't given, it just shows player's inventory with armor/shield slot.

And mods like Baubles put additional background image to inventory slot to show what that slot is for(amulet, belt etc.) so showing that image in slot background would be good.


Sorry for just giving you idea. I don't know how to implement my idea to real things.
And good thing that modder is actively developing mod. Thank you.

**Comment by MairwunNx** [comment]
With small hacks I achieved such a result

Left is inventory opened via (at now via `/test2` command :DD)
And right actual player inventory.

Is allow any manipulations with it, for example item move and taking and giving.

![image](https://user-images.githubusercontent.com/39625750/83164683-2f68bd80-a115-11ea-959e-4bea042cf672.png)

As you see we have 4 free slots, it slots unused, and if we move any item to last 4 slots - we just lost this item.

Also, we can't see other player inventory if we getting back on some distance of player.
I found this code in class `PlayerInventory`.

![image](https://user-images.githubusercontent.com/39625750/83165159-cdf51e80-a115-11ea-86ed-24f1e11dc8a4.png)

**Comment by MairwunNx** [comment]
You mean support other mods? I don't know about it. But maybe solution upper support it.

**Comment by TetraTheta** [comment]
> With small hacks I achieved such a result
> 
> Left is inventory opened via (at now via `/test2` command :DD)
> And right actual player inventory.
> 
> Is allow any manipulations with it, for example item move and taking and giving.
> 
> ![image](https://user-images.githubusercontent.com/39625750/83164683-2f68bd80-a115-11ea-959e-4bea042cf672.png)
> 
> As you see we have 4 free slots (But it's good for "trash" slot =)), it slots unused, and if we move any item to last 4 slots - we just lost this item.
> 
> Also, we can't see other player inventory if we getting back on some distance of player.
> I found this code in class `PlayerInventory`.
> 
> ![image](https://user-images.githubusercontent.com/39625750/83165159-cdf51e80-a115-11ea-86ed-24f1e11dc8a4.png)

That's exactly what EssentialsX did to manage other player's inventory. Great work!

As far as I remember, EssentialsX could access any player who is online. It didn't care about distance or difference of dimension between executor and the player. If the target is online, wherever executor is, he can see target's inventory. So, if possible, it would be good option to leave it to users to determine whether to use 'maximum distance'.

Supporting other mod's inventory would be another problem so you can put it on the back burner.

**Comment by MairwunNx** [comment]
At now problem with distance fixed. It works good I think. (You can see positions diff on the screenshot)

![image](https://user-images.githubusercontent.com/39625750/83169754-29c2a600-a11c-11ea-8095-3d54ff265e27.png)

Also I added checking for clicking to danger slots, by default just will cancel this action, but in settings we can disable danger slots protection and any items in danger slots will lost.

**Comment by MairwunNx** [comment]
Checking for permissions to editing opened inventory and exempt ability also added.
