### ISSUE TITLE
gamemode change shortcut like '/gms', '/gmc', '/gmsp' etc.

### ISSUE THREAD

**Issue by TetraTheta** [ProjectEssentials/ProjectEssentials#23]
EssentialsX has gamemode shortcut command like `/gms` which is same as `/gamemode survival`. It would be helpful because with this, user doesn't need to type all 'gamemode survival'.

`/gms` : `/gamemode survival`
`/gmc` : `/gamemode creative`
`/gma` : `/gamemode adventure`
`/gmsp` : `/gamemode spectator`

Of course, these command can accept target like `/gms <player>` and if target is not specified, target would be the command issuer. And It should accept target as wildcard like `@a`, `@p` etc.
I don't know original EssentialsX command can accept multiple targets like `/gms <player1> <player2> <player3>` but if it can, implementing it would be nice.

**Comment by MairwunNx** [comment]
Hi again, @TetraTheta! 👋

This feature already implemented in `core` module (included in `2.0.0`).
IDK accept it selectors or no, but it will accept all argument types vanilla requires.

gmc\gms\gmsp\gma implemented as redirects to gamemode <mode>.
