### ISSUE TITLE
Pages for /help command

### ISSUE THREAD

**Issue by seisatsu** [ProjectEssentials/ProjectEssentials#6]
The listing from the /help command is too long; there isn't enough scrollback to read it all. It will be impossible to see the entire output from /help unless it is split into pages.

**Comment by MairwunNx** [comment]
Thanks for the idea, this will be implemented in future versions. 🥰👍

**Comment by MairwunNx** [comment]
@seisatsu This should show a "quick use example" of the command (i.e. as in the vanilla implementation of the `/help` command)? Or just commands list, without showing quick use example?

**Comment by MairwunNx** [comment]
@seisatsu Did you mean this? These are preliminary changes.

![image](https://user-images.githubusercontent.com/39625750/74463638-2b38cd00-4ea3-11ea-8943-ff228c6f8a78.png)

**Comment by seisatsu** [comment]
Yes, something like that is what I had in mind. You would view pages by running `/help <pagenum>`. The `/help` command by itself would return the first page only.

**Comment by MairwunNx** [comment]
@seisatsu Ok. Yes, by default just `/help` returned result for first page, and with `/help <page>` we can navigate between pages.

Also in configuration will available `maxLines` _by default 8_ (lines for one page) and `replaceDefault` _by default true_ (if value true then native (from vanilla) `help` command implementation will be replaced).

Thanks, i will close it issue when i commit changes.

**Comment by MairwunNx** [comment]
## ✔ Resolved. Implemented in cd9067b
