### ISSUE TITLE
/back command

### ISSUE THREAD

**Issue by seisatsu** [ProjectEssentials/ProjectEssentials#7]
A common feature in other essentials mods is a `/back` command, which teleports the player back to the coordinates from before their last teleport or death. I would like to request that this be implemented in a future version.

**Comment by MairwunNx** [comment]
Thanks for feature request 🙂, command will be implemented in `1.14.4-1.0.0` and in `1.15.2-1.1.0`.

**Comment by MairwunNx** [comment]
## ✔ Resolved in core module and added support with project essentials commands.
