### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by EvilBorty** [ProjectEssentials/ProjectEssentials#8]
Wasn't sure if this was a bug or not but when running commands it returns something like this:

project_essentials_chat.cooldown_not_expired

this comes with running any command including /tpa /spawn etc

Steps to reproduce the behavior
Go to '...' run this mod on forge version 31.1.12. I am running this mod with alot of other mods included in the Valhelsia 2 modpack: https://www.curseforge.com/minecraft/modpacks/valhelsia-2
Enter command '....' any command /home /tpa etc.
See error
error shown above
Expected behavior
when sending a tpa something like teleport request sent
Screenshots
Environment information
Project Essentials Core version: [e.g. v1.0.0.0]
Project Essentials version: [e.g. v0.6.0.0]
Project Essentials Modules version: [e.g. Spawn - v1.0.0.2; Home - v1.3.0.0]
Minecraft / Forge version: [e.g. 1.14.4 / 28.1.0]
Additional context

**Comment by MairwunNx** [comment]
Download localization resource pack from this link and apply in resource-pack menu.

https://github.com/ProjectEssentials/ProjectEssentials-Localization/releases/download/v1.1.0/ProjectEssentials-Localization-1.15.2-all.zip

**Comment by MairwunNx** [comment]
if you use server-side only mod, then you need paste this link to `resource-pack` property as value (in `server.properties`).

**Comment by MairwunNx** [comment]
Probably resolved in new mod version. Check it. ✔

**Comment by MairwunNx** [comment]
If this issue will reproduced by someone more open this.
