### ISSUE TITLE
not letting me edit

### ISSUE THREAD

**Issue by MacWhinny** [ProjectEssentials/ProjectEssentials#9]
HI. i'm trying to do the ingame commands to change anything and when i put in commands i get this https://gyazo.com/bb2507b8b89bc8d48b0cc0b3b4afcd6a

I've myself as owner and i'm OP

**Comment by MairwunNx** [comment]
Hello, @MacWhinny. Wich ingame commands? What you trying anything to commands?
You use mod as server-side-only mod? Or you downloaded mod-pack?

**Comment by MacWhinny** [comment]
Hi, looks like any that i try adding. When i set a permission for say your teleporter mod. so teleport.random It says restricted when i type /rtp. even though it's in the default rank 
https://gyazo.com/f6bdc34b9b5400e476db0907f4b92031
I added the mod from curse forge

**Comment by MairwunNx** [comment]
Still getting this issue? And `/rtp` command not exist in Project Essentials. It exist in my other mod "Random Teleport".

**Comment by MairwunNx** [comment]
Issue related to [Random Teleport](https://github.com/MairwunNx/RandomTeleport) repository, i don't understand your problem, if this will reproduced by someone more or by you - open this.
